version: '2'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: proxy
    links:
      - chat:chat
    ports:
      - 80:80
      - 443:443
  chat:
    build:
      context: .
      dockerfile: Dockerfile-chat
    image: chat
    expose:
      - 3000
