FROM nginx:latest

MAINTAINER Senio Caires <seniocaires@gmail.com>

COPY cfg/nginx.conf /etc/nginx/nginx.conf
COPY cfg/localhost.conf /etc/nginx/sites-enabled/localhost.conf

ADD certs /certs

EXPOSE 80 443
